name: Bedwars
version: 3.3.0.b1
api: 1.14.0
main: Bluplayz\BedWars
author: NetherTechnology
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
