name: Bedwars_Insane_Mode
version: 1.0.0
api: 1.14.0
main: Bedwars_Insane_Mode\Bedwars
author: NetherTechnology
commands:
    InsaneBedWars:
        description: Bedwars_Insane_Mode Main Command
        aliases: [ibw]
