name: Bedwars
version: 4.1.0
api: 1.14.0
main: Bluplayz\BedWars
author: NetherTechnology
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
